[package]
name = "notreux/multiplayer-game-demo"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
Remo = "littensy/remo@1.5.2"
UpsideEngine = "notreux/upsideengine@3.1.0"
t = "osyrisrblx/t@3.1.1"